version: '2'
services:
  firefox:
    image: selenium/standalone-firefox:2.53.1
    ports:
      - '127.0.0.1:4444:4444'
    network_mode: 'host'
  storage-ui:
    image: canfar/storage
    ports:
      - '127.0.0.1:8080:8080'
    network_mode: 'host'
    depends_on: 
      - 'firefox'
    environment:
      - CATALINA_OPTS="-DSSO_SERVERS=127.0.0.1 apps.canfar.net www.canfar.phys.uvic.ca"
