version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    image: nginx:alpine
    ports:
      - '443:443'
      - '80:80'
    networks:
      - 'storage'
    volumes:
      - './docker/proxy/default.conf:/etc/nginx/conf.d/default.conf'
      - './docker/proxy/html:/usr/share/nginx/html'
      - 'server_certs:/usr/share/nginx/certs'
    depends_on:
      - 'storage'
      - 'web-root'

  web-root:
    image: canfar/web-root:jdk11-slim
    networks:
      - 'storage'

  storage:
    image: canfar/storage:9-jdk13-slim
    ports:
      - '5555:5555'
    networks:
      - 'storage'
    environment:
      APP_REGISTRY_URL: https://proxy.cadc.dao.nrc.ca/reg/applications
      CATALINA_OPTS: -DSSO_SERVERS="jenkinsd.cadc.dao.nrc.ca www.canfar.net" -Dorg.opencadc.vospace.service_id=ivo://canfar.net/cavern

networks:
  storage:

volumes:
  server_certs:
    external: true
