version: '3.7'
services:
  proxy:
    image: traefik:v2.9
    hostname: nrc-023054.cadc.dao.nrc.ca
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    volumes:
      - "server_certs:/server_certs:ro"
      - "proxy_config:/configuration:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - "storage"
    networks:
      - "nrc-local"
  storage:
    image: tomcat:9-jdk11-openjdk-slim
    command: "catalina.sh run"
    entrypoint: "/entrypoint/entrypoint.sh"
    ports:
      - '5555:5555'
    networks:
      - 'nrc-local'
    volumes:
      - "entrypoint_root:/entrypoint:ro"
      - "./build/libs/storage.war:/usr/local/tomcat/webapps/storage.war"
      - "./docker/server.xml:/usr/local/tomcat/conf/server.xml:ro"
      - "/Users/jenkinsd/Projects/cadc/test-certificates/servops.pem:/root/.ssl/cadcproxy.pem:ro"
      - "/Users/jenkinsd/config/org.opencadc.vosui.properties:/root/config/org.opencadc.vosui.properties:ro"
      - "/Users/jenkinsd/config/LocalAuthority.properties:/root/config/LocalAuthority.properties:ro"
      - "/Users/jenkinsd/config/RsaSignaturePub.key:/root/config/RsaSignaturePub.key:ro"
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555 -Dca.nrc.cadc.auth.IdentityManager=ca.nrc.cadc.ac.ACIdentityManager -Dorg.opencadc.vosui.mode=dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.storage.loadbalancer.server.port=8080"
      - "traefik.http.routers.storage.rule=(Host(`nrc-023054.cadc.dao.nrc.ca`) && PathPrefix(`/storage`))"
      - "traefik.http.routers.storage.entrypoints=websecure"
      - "traefik.http.routers.storage.service=storage"
      - "traefik.http.routers.storage.tls=true"
      - "traefik.http.routers.storage.tls.domains[0].main=cadc.dao.nrc.ca"
      - "traefik.http.routers.storage.tls.domains[0].sans=*.cadc.dao.nrc.ca"

networks:
  nrc-local:
    external: true

volumes:
  server_certs:
    external: true
  proxy_config:
    external: true
  entrypoint_root:
    external: true

