# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Storage UI build

on:
  push:
    branches: [ master, github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew -i clean build test
    - name: Docker build
      run: docker build -t opencadc/storage:SNAPSHOT .

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check docker-compose
        run: docker-compose -v
